blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index')
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

maxmeat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('shop.urls')),
    path('poll/', include('poll.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

shop/urls.py
from . import views
from django.urls import path


app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('products/', views.product_list, name='product_list'),
    path('products/<str:category_slug>/', views.product_list, name='product_list_by_category'),
    path('products/<int:id>/<str:slug>/', views.product_detail, name='product_detail'),
]

blog/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()


class Entry(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    entry_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, default=0, on_delete=models.CASCADE)

cart/models.py
from django.db import models

# Create your models here.

poll/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published Recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):

    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):

    category = models.ForeignKey(Category, related_name='products', on_delete='cascade')
    price = models.DecimalField(decimal_places=2, max_digits=10)
    name = models.CharField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
    )

    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput,
    )

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):

    return HttpResponse("Hello, you are at the index")

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            update_quantity=cd['update'],
        )

    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

poll/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
# Create your views here.
from .models import Question, Choice
from django.views import generic
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'poll/index.html'
    context_object_name = 'recent_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'poll/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'poll/results.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


def vote(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'poll/detail.html', {
            'question': question,
            'error_message': 'You didn\'t select a valid choice',
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully
        # dealing with POST data. This prevents data from being
        # posted twice if a user hits the back button

        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from cart.forms import CartAddProductForm

# Create your views here.


def index(request):

    return render(request, 'shop/index.html')


def about(request):

    return render(request, 'shop/about.html')


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category, available=True)
    return render(request, 'shop/products/list.html', {
        'category': category,
        'categories': categories,
        'products': products
    })


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(
        request,
        'shop/products/detail.html',
        {
            'product': product,
            'cart_product_form': cart_product_form,
        }
    )

cart/templates/cart/detail.html
{% extends 'shop/layout.html' %}

{% load static %}

{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit Price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static '/shop/no_image.png' %}{% endif %}"/>
                        </a>
                    </td>
                    <td>
                        {{ product.name }}
                    </td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {{ item.update_item_quantity.quantity }}
                            {{ item.update_item_quantity.update }}
                            <input type="submit" value="Update">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td>
                        <a href="{% url 'cart:cart_remove' product.id %}">Remove</a>
                    </td>
                    <td class="num">£{{ item.price }}</td>
                    <td class="num">£{{ item.total_price }}</td>
                </tr>
                {% endwith %}
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

maxmeat/templates/maxmeat/layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'maxmeat/style.css' %}"/>
<head>
    <meta charset="UTF-8">
    <title>Max Meat</title>
</head>
<body>
<div class="col-lg-4">
{% block content %}
{% endblock %}
</div>
</body>
</html>

poll/templates/poll/detail.html
{% extends 'poll/layout.html' %}

{% block content %}
    <h3>{{ question.question_text }}</h3>
    <p>{{ question.pub_date }}</p>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'poll:vote' question.id %}" method="post">
    {% csrf_token %}
    <ul>
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{  forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
        {% endfor %}
        <input type="submit" value="Vote" />
    </ul>

    <a href="{% url 'poll:index' %}">Back</a>
{% endblock %}

poll/templates/poll/index.html
{% extends 'poll/layout.html' %}

{% block content %}
    {% if recent_question_list|length < 1 %}
        <h3>No polls are available.</h3>
    {% else %}
        <h3>Recent Polls:</h3>
        <div class="container">
        <ul>
    {% for question in recent_question_list %}
        <li><a href="{% url 'poll:detail' question.id %}">{{ question }}</a></li>
    {% endfor %}
        </ul>
        </div>
    {% endif %}

{% endblock %}

poll/templates/poll/layout.html
<title>Max Meat Shop Guildford</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'poll/style.css' %}"/>
<div class="container">
    <body>
        <h2>This is the poll site</h2>
        <br/>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</div>

poll/templates/poll/results.html
{% extends "poll/layout.html" %}

{% block content %}
    <h1> {{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'poll:detail' question.id %}">Vote Again?</a>
{% endblock %}

shop/templates/shop/about.html
{% extends 'shop/layout.html' %}

{% block content %}
    <h3>About Max's Meat</h3>
    <div class="jumbotron">
        <p>Max meat was started in  2018 by a totally incompetent butcher</p>
        <p>Instead of starting his own shop, he bought a plot from sme other guys,
        who realised that they weren't making any money.</p>
        <p>This is the story of how Max Broadhurst-Jones went bankrupt.</p>
    </div>
{% endblock %}

shop/templates/shop/index.html
{% extends 'shop/layout.html' %}

{% block content %}
    <h3>This is the shop home page</h3>
    <div class="jumbotron">
        <p>This is where the general information about the shop will go
        such as opening times and location</p>
        <ul>
            <li>Mon - Closed</li>
            <li>Tues - Closed</li>
            <li>Weds - Closed</li>
            <li>Thurs - Closed</li>
            <li>Fri - Closed</li>
            <li>Sat - Closed</li>
            <li>Sun - Closed</li>
        </ul>
    </div>
{% endblock %}

shop/templates/shop/layout.html
<title>Max Meat Shop Guildford</title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'shop/style.css' %}"/>
<div class="container">
{% include 'shop/navbar.html' %}
</div>
<div class="container">
    <body>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</div>

shop/templates/shop/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'shop:index' %}">Maximum Meat</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        {% url 'shop:index' as index %}
        {% url 'shop:about' as about %}
        {% url 'shop:product_list' as products %}
      <a class="nav-item nav-link {% if request.path == index %} active {% endif %}" href="{% url 'shop:index' %}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link {% if request.path == about %} active {% endif %}" href="{% url 'shop:about' %}">About</a>
      <a class="nav-item nav-link {% if request.path == products %} active {% endif %}" href="{% url 'shop:product_list' %}">Products</a>
    </div>
  </div>
<div>
    {% with total_items=cart|length %}
        {% if cart|length > 0 %}
        Your cart:
        <a href="{% url 'cart:cart_detail' %}">
            {{ total_items }} item{{ total_items|pluralize }}, £{{ cart.get_total_price }}
        </a>
        {% else %}
        Your cart is empty
        {% endif %}
    {% endwith %}
</div>
</nav>

shop/templates/shop/products/detail.html
{% extends 'shop/layout.html' %}
{% load static %}

{% block content %}

    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'shop/no_image.png' %}{% endif %}"/>
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">£{{ product.price }}</p>
        <form action="{% url 'cart:cart_add' product.id %}" method="POST">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
        </form>
        {{ product.description|linebreaks }}
    </div>

{% endblock %}

shop/templates/shop/products/list.html
{% extends 'shop/layout.html' %}

{% load static %}

{% block content %}

    <title>{% if category %}{{ category.name }}{% else %}Product{% endif %}</title>

    <div class="wrapper">

    <nav class="navbar">

        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url 'shop:product_list' %}">All</a>
            </li>
        {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
        {% endfor %}
        </ul>
    </nav>
    </div>


    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'shop/no_image.png' %}{% endif %}"/>
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br/>
                £{{ product.price }}
            </div>
        {% endfor %}
    </div>

{% endblock %}